---
title: Flow of Question
---
flowchart
    A{Question} --> B[Client-Task]
    A --> C[Contractor]
    A --> L[Leave]
    A --> S[Share]
    B --> F[Follow up]
    B --> E[Scoping Document]
    L --> E
    C --> E
    C --> T[ToDo]
    M --> T
    S --> M[Meeting]
    S --> T
    T --> E
    S --> E
    classDef green fill:#9f6,stroke:#333,stroke-width:2px;
    classDef orange fill:#f96,stroke:#333,stroke-width:4px;
    classDef purple fill:#939,stroke:#333,stroke-width:4px, color: #fff;
    classDef blue fill:#33c,stroke:#333,stroke-width:4px, color: #fff;
    class A blue
    class F,T,L purple
    class E green
    class B,C,D,S,M orange